### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by SpakeLee** [LesFerch/IEModeExpiryFix#2]
![image](https://github.com/LesFerch/IEModeExpiryFix/assets/66896825/9336d433-a85f-49b1-8243-3064b68a07e5)

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/66896825/af53b14d-8363-4877-9e82-d056a6c3aa0e)

script not working....

**Comment by LesFerch** [comment]
When I test your Preferences file, Edge says it's corrupted:
![image](https://github.com/LesFerch/IEModeExpiryFix/assets/79026235/f7f37657-1746-4021-b638-e263f04d4ae3)

So, I manually added, the only IE Mode page I see in your Preferences file, to my IE Mode pages:
![image](https://github.com/LesFerch/IEModeExpiryFix/assets/79026235/a1c64ef8-7294-44af-8979-6e01915a28f5)

Then I ran the script and the expiry date was correctly updated:
![image](https://github.com/LesFerch/IEModeExpiryFix/assets/79026235/47d0ab18-71c4-4f92-9da0-476e4beace59)

I don't see any issue with the script. I only see an issue with your Preferences file.

However, the site http://bpm.diodes.com does not exist. Is that the page you wanted to add?

Did you run the script as is? If you edited the script in any way, please send me your edited version.

**Comment by SpakeLee** [comment]
i did'nt change the script,my step is add the web site and double click the script.
then get same message...

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/66896825/19961848-95b0-4a93-8e9b-fef2611fd6f8)

**Comment by SpakeLee** [comment]
please help me to cover any about diodes’s url, thank you

LesFerch ***@***.***>於 2023年6月27日 週二，上午12:23寫道：

**Comment by LesFerch** [comment]
I don't know why your Preferences file is getting corrupted. I tested with the same Edge version on Windows 11 build 22621.1848. Everything works fine for me. I could try setting my system language and regional settings to match your system, in case that makes a difference. Can you post a screenshot of your Region control panel and your Language and region setting screen?

**Comment by SpakeLee** [comment]
![image](https://github.com/LesFerch/IEModeExpiryFix/assets/66896825/47fdda04-4314-4743-85c5-91735859420d)

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/66896825/49e7768d-e484-4409-a178-a87e97fd1338)

Taiwan and Traditional Chinese

**Comment by LesFerch** [comment]
> Taiwan and Traditional Chinese

Thanks. 🙂

**Comment by LesFerch** [comment]
It still works fine for me even with everything set to Taiwan and Traditional Chinese.

Have you tried deleting the Preferences file so that Edge creates a new one?

If that doesn't work, I suggest trying the PowerShell version of the script.

**Comment by SpakeLee** [comment]
still not working... T . T

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/66896825/13153122-abd1-47d5-90af-ddd8813854d3)

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/66896825/ca977b78-3e24-4bc6-9cdc-9cac0089ba13)

**Comment by LesFerch** [comment]
Did you try deleting the Preferences file?

**Comment by SpakeLee** [comment]
> 您是否嘗試刪除首選項文件？

Yes,i try delete the preferences file.

**Comment by LesFerch** [comment]
I see a "sitelist_data_2" section in your Preferences file. It looks like your Edge settings are centrally managed. If so, the expiry can be set by your IT department, as per the documentation [here](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/what-is-enterprise-mode).

Please confirm and let me know. Thanks.

**Comment by SpakeLee** [comment]
yes it is managed.so i can't use the script to extend date?

**Comment by LesFerch** [comment]
That's my conclusion. Your IT department would have to add that page to the site list with an extended expiry. If they can't, or won't, do that, I can only suggest an alternate solution...

You can save a [simple three line script](https://github.com/LesFerch/SampleCode/blob/main/VBS-misc/LaunchIE.vbs) that will open that page directly in IE. It's really no different then opening in IE Mode because that mode also uses IE to open the page (you may have noticed iexplore.exe in your task list when the page is open). Just change `about:blank` in the script to the URL you need. There's no added risk accessing the page that way, as long as you don't use IE as a general purpose browser.
