### ISSUE TITLE
PowerShell Script Changes User's Region Setting

### ISSUE THREAD

**Issue by Noonedefault** [LesFerch/IEModeExpiryFix#4]
When run in a pt-PT windows 10, script changes region to en-Us. 
It is possible to change code to not affect region?
Thanks.

**Comment by LesFerch** [comment]
The region setting in the script simply tells the script how to interpret the date format on the following line. It should have no effect on anything outside of the script. Are you saying your machine's region setting actually changed to en-US?

**Comment by Noonedefault** [comment]
Yes. Correct. I noticed that cause hour changed to PM at taskbar.

**Comment by Noonedefault** [comment]
Please notice that vbs execution is ok.

PS1 has the behavior.

**Comment by LesFerch** [comment]
Now I know to look at the PS1 version. I assumed the region setting in the PS1 script would be specific to the script, like it is in VBS. I'll look for a fix. Thank you!

**Comment by Noonedefault** [comment]
Thank you very much. :)

**Comment by LesFerch** [comment]
Fixed.
