### ISSUE TITLE
msedge 119.0.2151.93  is not work?

### ISSUE THREAD

**Issue by uranus829** [LesFerch/IEModeExpiryFix#5]
Hello,
My msedge language:zh-cn
After running the script, the time still does not change.
![image](https://github.com/LesFerch/IEModeExpiryFix/assets/46716344/63c9b4ac-b3a4-4a94-8a78-38244d4cc65b)

**Comment by LesFerch** [comment]
The script works with all languages, including zh-CN. Assuming you did not modify the script, the most likely explanation is that your Edge profile is centrally managed. As per the readme:

**Note**: The script will not work if your Edge profile is centrally managed (i.e. controlled by your IT department).

If that is the case, I recommend using [LaunchIE](https://lesferch.github.io/LaunchIE/).

**Comment by LesFerch** [comment]
Here are screenshots of a test I ran with my language and regional settings set to Chinese. Everything worked fine. I did NOT make any change to the script. The locale in the script must remain set to "en-US".

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/79026235/37409d88-8efe-4642-ae9e-47892172771b)

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/79026235/d5fe7b54-9942-4ff4-bef3-81ece1ea3c6a)

**Comment by uranus829** [comment]
> The script works with all languages, including zh-CN. Assuming you did not modify the script, the most likely explanation is that your Edge profile is centrally managed. As per the readme:
> 
> **Note**: The script will not work if your Edge profile is centrally managed (i.e. controlled by your IT department).
> 
> If that is the case, I recommend using [LaunchIE](https://lesferch.github.io/LaunchIE/).

Hello, Windows 10 msedge does not have centralized management, it is all in stand-alone mode.Is it possible to add the url through the registry or script?

**Comment by LesFerch** [comment]
I tested again on Windows 11 with language set to Chinese Simplified (zh-CN), Country set to China, and Regional format set to Chinese (Simplified, China). Everything worked correctly with both the VBS and PS1 scripts.

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/79026235/8a73ab3a-6c29-4e4f-b1d9-d32c82d249e9)
