### ISSUE TITLE
Can you add reg or parameter values to the URL?

### ISSUE THREAD

**Issue by uranus829** [LesFerch/IEModeExpiryFix#6]
I want to enable IE mode and add URL through script or registry. Is there any way?Thank you!

**Comment by LesFerch** [comment]
Uncomment and edit the `AddPages` line. Line 43 in the VBS script or line 46 in the PowerShell script.

**Comment by uranus829** [comment]
> Uncomment and edit the `AddPages` line. Line 43 in the VBS script or line 46 in the PowerShell script.
I'll try it, thank you!

**Comment by uranus829** [comment]
> Uncomment and edit the `AddPages` line. Line 43 in the VBS script or line 46 in the PowerShell script.

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/46716344/c85bb840-f84b-41f1-b836-897a20b2236b)

I added the following line, not working?
AddPages = "http://www.baidu.com/"

**Comment by LesFerch** [comment]
Your edit is correct.
I do not know why the script fails to find any profiles to process.
Is the result the same with the PowerShell script?

**Comment by uranus829** [comment]
> PowerShell script

PowerShell script results are the same.

**Comment by LesFerch** [comment]
Can you test on another computer or in a VM?

**Comment by uranus829** [comment]
> Can you test on another computer or in a VM?

After importing, open edge and display:
User configuration error
We were unable to read your preferences or save preference changes. You may not be able to use all features.

**Comment by LesFerch** [comment]
Maybe there was some conflict with its initial Edge setup. Make sure Edge is settled down and working correctly and try it again. If it still fails to work correctly, then you may be out of luck. The only issues I have seen are with managed computers, but if your Edge profile is not managed, I have no explanation.

As I mentioned before, an alternative solution is to use [LaunchIE](https://lesferch.github.io/LaunchIE/).

**Comment by uranus829** [comment]
> Maybe there was some conflict with its initial Edge setup. Make sure Edge is settled down and working correctly and try it again. If it still fails to work correctly, then you may be out of luck. The only issues I have seen are with managed computers, but if your Edge profile is not managed, I have no explanation.
> 
> As I mentioned before, an alternative solution is to use [LaunchIE](https://lesferch.github.io/LaunchIE/).

I confirmed that the AddPages parameter was affected, because after I deleted the user configuration file, I tried to comment the AddPages parameter, and it was normal to modify the expiration date. Then, I removed the comment, ran the script, and when I opened EDGE, it prompted a user configuration error.

**Comment by LesFerch** [comment]
Can you post your configuration file (the one prior to running the script)? I would like to see if I can recreate the error. Just to confirm, the script now works correctly for changing the date, as long as you don't use the AddPages feature? And that works with both the VBS and PS1 scripts? Does the AddPages cause the same error with the PS1 script?

**Comment by uranus829** [comment]
[IEModeExpiryFix.zip](https://github.com/LesFerch/IEModeExpiryFix/files/14413960/IEModeExpiryFix.zip)
yes,PS1 script  cause the same error.

**Comment by LesFerch** [comment]
To recreate the error, I need your Preferences file. It's usually in the Default folder:

`%LocalAppData%\Microsoft\Edge\User Data\Default\Preferences`

**Comment by uranus829** [comment]
> To recreate the error, I need your Preferences file. It's usually in the Default folder:
> 
> `%LocalAppData%\Microsoft\Edge\User Data\Default\Preferences`

[Preferences.zip](https://github.com/LesFerch/IEModeExpiryFix/files/14415493/Preferences.zip)
![1](https://github.com/LesFerch/IEModeExpiryFix/assets/46716344/ac5d0c2e-689a-4754-abe8-5611593aee90)

**Comment by LesFerch** [comment]
I tested with your Preferences file and your copy of the script and it all worked correctly. There were no errors and the Preferences file was properly updated. I don't know why it doesn't work on your computer.

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/79026235/24dd743b-3eb0-460a-a8ae-276872c86573)

**Comment by LesFerch** [comment]
One idea I have is that something is causing Edge to reopen automatically as soon as it's killed by the script. That could explain the corruption. Maybe some widget.

**Comment by uranus829** [comment]
> One idea I have is that something is causing Edge to reopen automatically as soon as it's killed by the script. That could explain the corruption. Maybe some widget.

Thank you, that's all I can do for the time being.

**Comment by LesFerch** [comment]
> Thank you, that's all I can do for the time being.

Understood. One last question. Are you running any third-party AV, such as BitDefender?
