### ISSUE TITLE
Preferences file updates backed out on launching Edge

### ISSUE THREAD

**Issue by glkeswick** [LesFerch/IEModeExpiryFix#7]
I have used IEModeExpiryFix.vbs to set a long expiry date on three pages I had added to "Internet Explorer mode pages" in Edge settings. The script runs fine and I checked in the updated Preferences file to confirm the date_added value was updated for all three pages. However, as soon as I launch Edge the Preferences file gets updated to set the date_added values back to their original dates. 

I cannot track down where Edge is getting its data from to overwrite the updated Preferences file with the previous version.

I'm sure this isn't a problem with your script because it also occurs if I manually edit Preferences using a text editor to paste 15741381600000000 in the date_added value. 

Some environment information:

Windows 11 Home (64 bit) Version 10.0.22631 Build 22631
Edge 124.0.2478.51 (Official build) (64-bit)
It is my personal PC which is not administered centrally by an IT team and never has been.
I am not signed in to Edge on my PC and it is not synching settings etc
I do run Edge on my phone and found that it was signed into my account and was synching, but I have now signed out and stopped synching but the problem still occurs

Do you have any idea what might be the cause of this behaviour?

**Comment by glkeswick** [comment]
> It sounds like your Edge profile is centrally managed. Is this a work computer?

No it isn't and never has been. I bought it and have been the only owner and user.

**Comment by LesFerch** [comment]
Sorry, I now see that was in your original comment. Microsoft seems to keep adding more processes that use Edge, so something may have changed. Or it may be triggered by a specific configuration. If I'm sitting in front of a machine where I can replicate the behavior, I may be able to figure out what's going on. I usually start by creating a new local user account and see if it works there, If so, I start looking for differences between the two account profiles. I might find something quickly or it may take many hours.

An alternative solution is to launch IE directly for those legacy websites. You can use my [LaunchIE](https://lesferch.github.io/LaunchIE/) tool for that. Just set up a shortcut for each web site.

**Comment by glkeswick** [comment]
> Sorry, I now see that was in your original comment. Microsoft seems to keep adding more processes that use Edge, so something may have changed. Or it may be triggered by a specific configuration. If I'm sitting in front of a machine where I can replicate the behavior, I may be able to figure out what's going on. I usually start by creating a new local user account and see if it works there, If so, I start looking for differences between the two account profiles. I might find something quickly or it may take many hours.
> 
> An alternative solution is to launch IE directly for those legacy websites. You can use my [LaunchIE](https://lesferch.github.io/LaunchIE/) tool for that. Just set up a shortcut for each web site.

I tried LaunchIE and after an initial problem got it to work so that does provide a work around but I'd prefer to just use Edge in compatibility mode. I'll continue trying to work out how to solve the problem with the Preferences file update and will post again if I find anything. Just to repeat, I know the problem isn't caused by your code so I'm not expecting you to spend any time on this unless your interest is piqued and/or you get other reports of the problem.

Thanks for your help.

**Comment by LesFerch** [comment]
Definitely interested. It's likely to happen to others, so it would be good to know what's going on. Let me know what happens when you test with another user account.

Please note that IE Mode uses ieplore.exe. It just redirects to an Edge window. As far as I can determine, it's identical from a security point of view. I think the main difference would come into play when setting up for someone else that may use the shortcut for the IE specific page and then continue to try to use that window for general browsing.

**Comment by glkeswick** [comment]
> Definitely interested. It's likely to happen to others, so it would be good to know what's going on. Let me know what happens when you test with another user account.
> 
> Please note that IE Mode uses ieplore.exe. It just redirects to an Edge window. As far as I can determine, it's identical from a security point of view. I think the main difference would come into play when setting up for someone else that may use the shortcut for the IE specific page and then continue to try to use that window for general browsing.

I created another local user account on my PC without creating a Microsoft account to go with it. In Edge settings I added some pages to be opened in IE mode, then ran your vb script to set the long expiry date and it worked!

So that suggests it is something to do with my normal account but where to start looking? Out of interest I deleted the Preferences file and relaunched Edge - this re-built the Preferences file complete with the previously configured IE mode pages and original "date_added" values. So I'm still wondering where Edge gets this data from to be able to re-create and overwrite the Preferences file.

**Comment by glkeswick** [comment]
Another experiment. I created a new profile (Profile 2) in Edge and did not link it to a Microsoft account. In Edge settings I switched to Profile 2 and added the same set of pages to be loaded in IE mode. After running IEModeExpiryFix.vbs date_added was updated with the long expiry date in Preferences in both Profile 1 and Profile 2.

After launching Edge date_added in Preferences in Profile 1 had reverted to the original date but in Profile 2 it remained as the long expiry date. So that at least tells me the behaviour is related to Profile 1 but I don't know where to look next for what is causing the behaviour. My suspicion is that even though I am not signed into Edge when using Profile 1 the mere fact that I have signed in and synchronised browser data at some time in the past means the Preferences file is always refreshed from a "master" copy/backup somewhere every time  Edge is launched and the only way to update the master is via the Edge UI.

**Comment by glkeswick** [comment]
I just discovered it is possible to configure site-based profile switching in Edge Profile preferences. This allows you to configure automatic switching to a specific profile when opening  a site. So in my case I have configured autoswitching to Profile 2 (which has the long IE mode expiry date) when opening the site I need to access in IE mode. This opens a new window rather than a new tab but I can live with that, although I must say, overall it is much easier to just use LaunchIE as you already suggested 🤣.

Would still like to figure out why my  Profile 1 preferences are overwritten on launching Edge, but if I never get to the bottom of that I do at least have two workarounds!

**Comment by LesFerch** [comment]
I played around with Edge on mobile, enabled sync, verified that favorites sync between mobile and desktop and then disabled sync and tested the script. It still worked fine for me. Without being able to replicate the issue, I'm at a loss to explain the issue you have with your Profile 1.

**Comment by glkeswick** [comment]
> I played around with Edge on mobile, enabled sync, verified that favorites sync between mobile and desktop and then disabled sync and tested the script. It still worked fine for me. Without being able to replicate the issue, I'm at a loss to explain the issue you have with your Profile 1.

Well thanks anyway for taking a look at it. I appreciate your support. If I find out what's causing this behaviour I will post back here in case anybody else runs up against the same issue.

**Comment by TGeRi** [comment]
We have the same problem!
- Edge without login
 - run iemodefix
 - Edge login
  --> the setting is gone. :(

**Comment by LesFerch** [comment]
There seems to be some combination of software or settings that cause Edge to behave like it's synced even when it's not. I'd have to find a way to replicate the behavior in order to have any chance of finding a solution. If you figure out a way to replicate the issue, starting from a new user profile, please let me know. In the meantime, all I can suggest is to use [LaunchIE](https://lesferch.github.io/LaunchIE/) instead.

**Comment by LesFerch** [comment]
The comments at [this Reddit link](https://www.reddit.com/r/MicrosoftEdge/comments/14kx0zv/stupid_edge_update_keeping_signing_me_in_and/) seem to describe the same problem. I didn't see any specific details that would help me replicate the issue, but there may be some clues there to follow when I have some time to experiment.

The OP said "It was a bug that was fixed in versions since my original post". Is there any chance you have updates paused or turned off and there's a newer Edge available?

**Comment by LesFerch** [comment]
I wonder if it makes any difference to turn off "Automatic sign in on Microsoft Edge" and "Allow single sign-on for work or school sites using this profile". I don't really expect those settings to make any difference if sync is off, but it couldn't hurt to try:

![image](https://github.com/LesFerch/IEModeExpiryFix/assets/79026235/a708b7ef-eb4f-4efc-b185-714aa1411b99)

**Comment by glkeswick** [comment]
Yes I already tried that. Or to be more accurate, I used to have it set on for my Profile 1 but turned it off when I ran into this problem but it made no difference. I created Profile 2 and have **_never_** signed in with it to Edge and the problem doesn't surface there.

So this makes me think that if a profile has **_ever_** been signed into Edge then it  is hosed from the point of view of making permanent edits to the preferences file. Seems like there is some kind of surreptitious log-in persisting and that seems to align with that Reddit thread if I understand it correctly.

**Comment by LesFerch** [comment]
I am closing this as "not planned" as I cannot recreate the issue, even after enabling/disabling Edge profile sync. As there are many environmental issues that can affect Windows behavior, it's possible that some day we'll find out how to replicate this issue on demand and then have an opportunity to look at potential solutions.
