### ISSUE TITLE
Support for running under System to update all user profiles

### ISSUE THREAD

**Issue by bradhs** [LesFerch/IEModeExpiryFix#9]
Is it possible to support running this under system?  Where it can determine the user logged in, and do a remote registry (I assume it has to do it that way?) to modify HKCU.

**Comment by LesFerch** [comment]
The script doesn't deal with the registry. It updates Edge profiles which are files stored within the user's profile folder. So, I think it should be possible to make a version that runs via the System account and updates all user profile folders. I'll look into that and post back.

**Comment by bradhs** [comment]
Thanks @LesFerch, after reviewing the script, it does appear that way.  I think the system has access to the user files, would be a great addition.

**Comment by LesFerch** [comment]
I changed the title to "Support for running under System to update all user profiles" since the current user's profile can already be updated silently by running the script in the user context with the $Silent switch set to $True.

**Comment by LesFerch** [comment]
The script now has an `AllUsers` variable that can be set to `True` to process all user profiles. This would typically be used with `Silent` set to `True` and with the script run via the SYSTEM account.
